# Generated by Django 4.2.30 on 2026-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_kg',
            field=models.TextField(blank=True, help_text='Кыргызча толук текст. Бош болсо — RU көрсөтүлөт.', verbose_name='Полный текст (KG)'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_text_kg',
            field=models.TextField(blank=True, help_text='Кыргызча кыскача сүрөттөмө. Бош болсо — RU көрсөтүлөт.', max_length=300, verbose_name='Краткое описание (KG)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kg',
            field=models.CharField(blank=True, help_text='Кыргызча которуу. Бош болсо, RU версиясы көрсөтүлөт.', max_length=200, verbose_name='Заголовок (KG)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Полный текст (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_text',
            field=models.TextField(max_length=300, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок (RU)'),
        ),
    ]
